// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpxYqS5ylcbmF7kiQNU94DvKhM8akJvI',
    appId: '1:296131056808:android:cb14e9aa19c9df81f8de9d',
    messagingSenderId: '296131056808',
    projectId: 'cab-booking-a8b7b',
    storageBucket: 'cab-booking-a8b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ98inRk9XZEOBXnQSw5cq7JYJf4FrgEI',
    appId: '1:296131056808:ios:f708410e2ac2ace6f8de9d',
    messagingSenderId: '296131056808',
    projectId: 'cab-booking-a8b7b',
    storageBucket: 'cab-booking-a8b7b.firebasestorage.app',
    androidClientId: '296131056808-e7raokqmmnf677gd8mp9p3ae2ejtrkcv.apps.googleusercontent.com',
    iosClientId: '296131056808-qh9uh6ps5ehn9a7b4h8g3r3a2qn2o1og.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6FjkHhqjfmKiuWyYgw0Y8Hf9xuGOiJU',
    appId: '1:296131056808:web:6224c485da7af035f8de9d',
    messagingSenderId: '296131056808',
    projectId: 'cab-booking-a8b7b',
    authDomain: 'cab-booking-a8b7b.firebaseapp.com',
    storageBucket: 'cab-booking-a8b7b.firebasestorage.app',
    measurementId: 'G-JZESXHWH4C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ98inRk9XZEOBXnQSw5cq7JYJf4FrgEI',
    appId: '1:296131056808:ios:f708410e2ac2ace6f8de9d',
    messagingSenderId: '296131056808',
    projectId: 'cab-booking-a8b7b',
    storageBucket: 'cab-booking-a8b7b.firebasestorage.app',
    androidClientId: '296131056808-e7raokqmmnf677gd8mp9p3ae2ejtrkcv.apps.googleusercontent.com',
    iosClientId: '296131056808-qh9uh6ps5ehn9a7b4h8g3r3a2qn2o1og.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb6FjkHhqjfmKiuWyYgw0Y8Hf9xuGOiJU',
    appId: '1:296131056808:web:9ba4d7c26624b1aef8de9d',
    messagingSenderId: '296131056808',
    projectId: 'cab-booking-a8b7b',
    authDomain: 'cab-booking-a8b7b.firebaseapp.com',
    storageBucket: 'cab-booking-a8b7b.firebasestorage.app',
    measurementId: 'G-XBZCJNMNBP',
  );

}